version: "3.7"
services:

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ./app_minio_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio minio123;
      /usr/bin/mc mb myminio/covers;
      /usr/bin/mc mb myminio/tracks;
      /usr/bin/mc --debug anonymous set public myminio/covers;
      /usr/bin/mc --debug anonymous set public myminio/tracks;
      exit 0;
      "

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "5432"
      POSTGRES_DB: "music_room"
    volumes:
      - ./app_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    depends_on:
      - createbuckets
      - minio

  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    environment:
      - REDIS_PASSWORD=6379
      - REDIS_PORT=6379
      - REDIS_DATABASES=0
    volumes:
      - ./app_redis_data:/data
    ports:
      - '6379:6379'